feat: support replicated architecture w/ sentinel
defenseunicorns/uds-package-valkey pull request #50
Opened 2024-11-16 02:20 UTC by JoeHCQ1

## Description

Enable replicated architecture instead of just standalone. This HA configuration is needed for a SWF bundle. Added tests as well to ensure it is actually working, and that it continues to work.

## Related Issue

Relates to https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/220

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [X] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-valkey/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-11-16 02:41 UTC, JoeHCQ1 commented on common/zarf.yaml
> -    actions:
This has to go because it couples valkey to the valkey namespace. I need to be able to deploy it to other namespaces both for the test and also in my SWF bundle

2024-11-18 20:50 UTC, Racer159 requested changes

2024-11-18 20:50 UTC, Racer159 commented on tests/zarf.yaml
> +            cmd: /bin/sh tests/watch-jobs.sh
```suggestion
            cmd: ./tests/watch-jobs.sh
            shell:
              linux: bash
              darwin: bash
```
the script uses bash-specific array syntax so needs shell preferences to work correctly.

2024-11-18 20:50 UTC, Racer159 commented on chart/templates/networking.yaml
> +      app.kubernetes.io/name: valkey
Would prefer `DestinationRule`s over `PeerAuthentication`s - Valkey uses the statefulset DNS name (which is routed to an IP eventually) but it is not a raw IP out the gate.  We can use this to still have mutual TLS in most scenarios with the only trandeoff being we need to have replica count be known to this chart as well (cc @zachariahmiller if he knows a way around that).  TLS is not enabled in the chart on Valkey's side by default so with a global peerauth exception node -> node traffic can be sniffed.  GitLab has a peerauth exception in it because of a different issue that will likely be fixed upstream in a uds-core update once ambient or native sidecars is enabled but would like to avoid adding PeerAuth exceptions if we can avoid it.

```suggestion
{{- range $i := until (int .Values.replicas) }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: valkey-headless-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
  - valkey-node-{{ $i }}.valkey-headless.{{ $.Release.Namespace }}.svc.cluster.local # Matches pod-specific DNS names
  ports:
  - number: 6379
    name: redis
    protocol: TCP
  location: MESH_INTERNAL
  resolution: NONE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: valkey-headless-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  host: valkey-node-{{ $i }}.valkey-headless.{{ $.Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      sni: valkey-node-{{ $i }}.valkey-headless.{{ $.Release.Namespace }}.svc.cluster.local
---
{{- end }}
```

2024-11-18 20:50 UTC, Racer159 commented on tests/watch-jobs.sh
this file should have execute permissions on it in `git`.

2024-11-18 20:50 UTC, Racer159 commented on tests/watch-jobs.sh
https://stackoverflow.com/questions/40978921/how-to-add-chmod-permissions-to-file-in-git#40979016

2024-11-18 20:50 UTC, Racer159 commented on tests/watch-jobs.sh
(it may also be better to refactor this into a jest test instead of a script though won't block for that)

2024-11-18 20:53 UTC, zachariahmiller commented on tasks.yaml
> +    actions:
`via`

2024-11-18 20:57 UTC, JoeHCQ1 commented on .github/workflows/test.yaml
> +      timeout: 60
Agreed - especially not since increasing the size of the runner. It's finishing in about 10 minutes.

2024-11-18 21:06 UTC, JoeHCQ1 commented on tasks.yaml
> +      - task: create-dev-package
I don't follow - note that in my not following I may have messed up a few other jobs too

2024-11-18 21:06 UTC, JoeHCQ1 commented on tasks.yaml
> +    actions:
same as above - I don't follow

2024-11-18 21:08 UTC, JoeHCQ1 commented on chart/templates/uds-package.yaml
> -        remoteGenerated: IntraNamespace
I thought I'd found that any traffic allowed on one end is implicitly allowed on the other. But that'd be rather insecure.

2024-11-18 21:13 UTC, Racer159 requested changes

2024-11-18 21:13 UTC, Racer159 commented on bundle/uds-bundle.yaml
> +          namespace: valkey-standalone
```suggestion
```

2024-11-18 21:13 UTC, Racer159 commented on bundle/uds-bundle.yaml
> +          namespace: valkey-standalone
```suggestion
```
We should leave this as is so that the upgrade tests are valid on this PR (likely will help with the resource issues on upgrade since it wouldn't create a 3rd deployment)

2024-11-18 21:13 UTC, Racer159 commented on bundle/uds-bundle.yaml
> +    ref: 0.1.0
do we need this?

2024-11-18 21:13 UTC, Racer159 commented on bundle/uds-bundle.yaml
> +    ref: 0.1.0
(it was copying before and was just fine)

2024-11-18 21:25 UTC, JoeHCQ1 commented on tasks/test.yaml
> +        default: ${UDS_ARCH}
From when I was fighting to get the architecture to be amd64 despite being on an m3 processor.

2024-11-18 21:25 UTC, JoeHCQ1 commented on tasks/test.yaml
> +        default: ${UDS_ARCH}
removed it

2024-11-18 21:26 UTC, JoeHCQ1 commented on tests/zarf.yaml
> +            cmd: /bin/sh tests/watch-jobs.sh
I love this - didn't know GH well enough to know I could do that so i removed the array and went to posix shell compliance.

2024-11-18 21:27 UTC, JoeHCQ1 commented on tests/zarf.yaml
> +            cmd: /bin/sh tests/watch-jobs.sh
Oh, that's Zarf anyway.

2024-11-18 21:39 UTC, Racer159 commented on tests/zarf.yaml
> +            cmd: /bin/sh tests/watch-jobs.sh
sorry I should have dig more - this shouldn't actually be necessary - the real reason it wouldn't work was that the script was not executable at first.

2024-11-18 21:52 UTC, zachariahmiller commented on tasks.yaml
> +  - name: test-bundle
why did you create this test-bundle task that just calls `test:all`? `test:all` is available in the context of this task file as well as running directly from the command line as `uds run test:all` without having to make this other task. The format and naming of these tasks is fairly standardized across packages as well so we'd prefer to not switch them up.

2024-11-18 21:55 UTC, JoeHCQ1 commented on tasks.yaml
> +  - name: test-bundle
I thought I could only call jobs with a top-level name. If that's available, no need for it.

2024-11-18 21:58 UTC, JoeHCQ1 commented on tasks.yaml
> +  - name: test-bundle
removed it

2024-11-18 22:35 UTC, Racer159 commented on tasks.yaml
> +      - task: create-dev-package
this shouldn't need to change - as is with this added here it will double create the package

2024-11-18 22:36 UTC, Racer159 commented on tasks.yaml
> +    actions:
I would like to maintain consistency for all packages and `test-bundle` is only a wrapper for `test:all` which can be called directly as `uds run test:all` so it is not actually needed or really doing anything here (just extra code to maintain)

2024-11-18 22:37 UTC, Racer159 commented on bundle/uds-bundle.yaml
> +    ref: 0.1.0
the Secrets that are in the config chart when `copyPassword` is used will be detected by Zarf and it should make the namespace - if it was not / is not then that is a bug and should be fixed

2024-11-18 22:38 UTC, Racer159 commented on tasks.yaml
> +          path: "src/"
```suggestion
```
the namespace package shouldn't be needed

2024-11-19 15:04 UTC, JoeHCQ1 commented
Going to update my SWF bundle that's deployed to my test cluster and then re-test - I am suspecting that the UDS version drift is the fault here - it all works on my dev cluster, but not in CI.

2024-11-20 19:19 UTC, JoeHCQ1 commented on bundle/uds-bundle.yaml
> +    ref: 0.1.0
removed it

2024-11-20 20:26 UTC, JoeHCQ1 commented on tasks.yaml
> +      - task: create-dev-package
It's not double-creating it - if I delete it I get the error:

```ERROR:  failed to create bundle: open zarf-package-valkey-amd64-8.0.1-uds.0.tar.zst: no such file or directory                                                                                                                                                                                
     ERROR:  Failed to run action: command "if [ "${FLAVOR}" != "registry1" ] || [ "${UDS_ARCH}" != "..." timed                                                                                                                                                                                         
             out after 0 seconds
```

2024-11-21 16:01 UTC, JoeHCQ1 commented on chart/templates/networking.yaml
> +      app.kubernetes.io/name: valkey
I'm suspecting I'll need to revert these changes to get it working locally again.

I'm getting this repeating error loop which I had before allowing permissive TLS - because once the sentinels tell the nodes about each other iirc they speak henceforth between themselves by IP, not statefulset DNS name.

```
1:X 21 Nov 2024 15:53:49.014 # +try-failover master mymaster valkey-node-1.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379                                                                                                       
1:X 21 Nov 2024 15:53:49.018 * Sentinel new configuration saved on disk                                                                                                                                                                              
1:X 21 Nov 2024 15:53:49.018 # +vote-for-leader ec189fc48ec98a607fe05216e70822709d7fb45d 24                                                                                                                                                          
1:X 21 Nov 2024 15:53:49.029 * c5130af90c4d1ee3099d9a3a74db66a2d1822643 voted for ec189fc48ec98a607fe05216e70822709d7fb45d 24                                                                                                                        
1:X 21 Nov 2024 15:53:49.029 * 1b5feeabba8c98009a891354822f4ac832eb5a2c voted for ec189fc48ec98a607fe05216e70822709d7fb45d 24                                                                                                                        
1:X 21 Nov 2024 15:53:49.074 # +elected-leader master mymaster valkey-node-1.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379                                                                                                     
1:X 21 Nov 2024 15:53:49.074 # +failover-state-select-slave master mymaster valkey-node-1.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379                                                                                        
1:X 21 Nov 2024 15:53:49.130 # +selected-slave slave valkey-node-0.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local:6379 valkey-node-0.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379 @ mymaster valkey-node-1.val
1:X 21 Nov 2024 15:53:49.130 * +failover-state-send-slaveof-noone slave valkey-node-0.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local:6379 valkey-node-0.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379 @ mymaste
1:X 21 Nov 2024 15:53:49.185 * +failover-state-wait-promotion slave valkey-node-0.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local:6379 valkey-node-0.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379 @ mymaster va
1:X 21 Nov 2024 15:53:49.769 * Sentinel new configuration saved on disk                                                                                                                                                                              
1:X 21 Nov 2024 15:53:49.769 # +promoted-slave slave valkey-node-0.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local:6379 valkey-node-0.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379 @ mymaster valkey-node-1.val
1:X 21 Nov 2024 15:53:49.769 # +failover-state-reconf-slaves master mymaster valkey-node-1.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379                                                                                       
1:X 21 Nov 2024 15:53:49.827 # +failover-end master mymaster valkey-node-1.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379                                                                                                       
1:X 21 Nov 2024 15:53:49.827 # +switch-master mymaster valkey-node-1.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379 valkey-node-0.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379                           
1:X 21 Nov 2024 15:53:49.829 * +slave slave valkey-node-2.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local:6379 valkey-node-2.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379 @ mymaster valkey-node-0.valkey-headl
1:X 21 Nov 2024 15:53:49.830 * +slave slave valkey-node-1.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local:6379 valkey-node-1.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379 @ mymaster valkey-node-0.valkey-headl
1:X 21 Nov 2024 15:53:49.835 * Sentinel new configuration saved on disk                                                                                                                                                                              
1:X 21 Nov 2024 15:54:49.877 # +sdown slave valkey-node-1.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local:6379 valkey-node-1.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379 @ mymaster valkey-node-0.valkey-headl
1:X 21 Nov 2024 15:54:49.878 # +sdown slave valkey-node-2.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local:6379 valkey-node-2.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379 @ mymaster valkey-node-0.valkey-headl
1:X 21 Nov 2024 15:54:50.053 * Sentinel new configuration saved on disk                                                                                                                                                                              
1:X 21 Nov 2024 15:54:50.053 # +new-epoch 25                                                                                                                                                                                                         
1:X 21 Nov 2024 15:54:50.056 * Sentinel new configuration saved on disk                                                                                                                                                                              
1:X 21 Nov 2024 15:54:50.056 # +vote-for-leader c5130af90c4d1ee3099d9a3a74db66a2d1822643 25                                                                                                                                                          
1:X 21 Nov 2024 15:54:50.651 # +config-update-from sentinel c5130af90c4d1ee3099d9a3a74db66a2d1822643 valkey-node-1.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 26379 @ mymaster valkey-node-0.valkey-headless.valkey-replicated-w-
1:X 21 Nov 2024 15:54:50.651 # +switch-master mymaster valkey-node-0.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379 valkey-node-1.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379                           
1:X 21 Nov 2024 15:54:50.654 * +slave slave valkey-node-2.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local:6379 valkey-node-2.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379 @ mymaster valkey-node-1.valkey-headl
1:X 21 Nov 2024 15:54:50.654 * +slave slave valkey-node-0.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local:6379 valkey-node-0.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379 @ mymaster valkey-node-1.valkey-headl
1:X 21 Nov 2024 15:54:50.658 * Sentinel new configuration saved on disk                                                                                                                                                                              
1:X 21 Nov 2024 15:55:50.674 # +sdown master mymaster valkey-node-1.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379                                                                                                              
1:X 21 Nov 2024 15:55:50.674 # +sdown slave valkey-node-2.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local:6379 valkey-node-2.valkey-headless.valkey-replicated-w-sentinel.svc.cluster.local 6379 @ mymaster valkey-node-1.valkey-headl
1:X 21 Nov 2024 15:55:50.811 * Sentinel new configuration saved o [...]

2024-11-21 19:57 UTC, JoeHCQ1 commented on chart/templates/networking.yaml
> +      app.kubernetes.io/name: valkey
scratch all that - it's working -  was totally missing the policies due to my missing replica field.

2024-11-21 22:48 UTC, Racer159 requested changes

2024-11-21 22:48 UTC, Racer159 commented on .github/workflows/test.yaml
> +        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
```suggestion
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
```

2024-11-21 22:48 UTC, Racer159 commented on .github/workflows/test.yaml
> +        uses: defenseunicorns/uds-common/.github/actions/test-flavor@164ce64c5cc775193a563db7e8ef9750ffefcdda  # v1.3.0
```suggestion
        uses: defenseunicorns/uds-common/.github/actions/test-flavor@164ce64c5cc775193a563db7e8ef9750ffefcdda # v1.3.0
```

2024-11-21 22:48 UTC, Racer159 commented on .github/workflows/test.yaml
> +    uses: defenseunicorns/uds-common/.github/workflows/callable-test.yaml@164ce64c5cc775193a563db7e8ef9750ffefcdda  # v1.3.0
```suggestion
    uses: defenseunicorns/uds-common/.github/workflows/callable-test.yaml@164ce64c5cc775193a563db7e8ef9750ffefcdda # v1.3.0
```

2024-11-21 22:48 UTC, Racer159 commented on bundle/uds-bundle.yaml
> +          namespace: valkey
```suggestion
```

2024-11-21 22:48 UTC, Racer159 commented on bundle/uds-bundle.yaml
> +          namespace: valkey
```suggestion
```

2024-11-21 22:48 UTC, Racer159 commented on chart/values.yaml
> +replicas: 3
```suggestion
replicas: 0
```

2024-11-21 22:48 UTC, Racer159 commented on bundle/uds-bundle.yaml
> +              value: 0  # Because this is the standalone instance.
Would prefer this to be the default
```suggestion
```

2024-11-21 22:48 UTC, Racer159 commented on bundle/uds-bundle.yaml
> +                secretKey: REDISCLI_AUTH
```suggestion
                secretKey: REDISCLI_AUTH
            - path: replicas
              value: 3  # Because replication is enabled and will spin up 3 replicas by default
```

2024-11-21 22:48 UTC, Racer159 commented on tasks.yaml
>        - task: setup:k3d-test-cluster
```suggestion
      - task: create-dev-package
      - task: setup:k3d-test-cluster
```

2024-11-21 22:48 UTC, Racer159 commented on tasks.yaml
> +      - task: create-dev-package
currently on `test-install` yes - but `create-dev-package` should not have been removed there (see other comment) - on `default` and `test-upgrade` it is running `create-dev-package` prior to `create-deploy-test-bundle` - this is how all of our other packages work and would like to keep the pattern consistent

2024-11-21 22:48 UTC, Racer159 commented on tasks/test.yaml
> +        default: ${UDS_ARCH}
```suggestion
```

2024-11-21 22:48 UTC, Racer159 commented on tasks/test.yaml
> +      - cmd: uds zarf package create tests --architecture="${{ .inputs.architecture }}" --confirm --skip-sbom
```suggestion
      - cmd: uds zarf package create tests --architecture="${UDS_ARCH}" --confirm --skip-sbom
```

2024-11-21 22:48 UTC, Racer159 commented on tasks/test.yaml
> +        default: ${UDS_ARCH}
```suggestion
```

2024-11-21 22:48 UTC, Racer159 commented on tasks/test.yaml
> +        cmd: uds zarf package deploy "zarf-package-valkey-test-${{ .inputs.architecture }}-0.1.0.tar.zst" --confirm
```suggestion
        cmd: uds zarf package deploy "zarf-package-valkey-test-${UDS_ARCH}-0.1.0.tar.zst" --confirm
```

2024-11-21 22:48 UTC, Racer159 commented on tests/zarf.yaml
> +            cmd: sleep 60
Is this still needed if we allow retries now? Would love to save the portion of this minute that is not needed in CI

2024-11-21 22:48 UTC, Racer159 commented on tests/valkey/test-job.yaml
> +              echo "${GET_OUTPUT}" | grep "${POD_NAME}" && echo "Got value via replica" || { echo "Failed to get value via replica. Output was: ${GET_OUTPUT}"; exit 1; }
Why do this 4 times in a row?

2024-11-21 23:05 UTC, zachariahmiller requested changes
Can you please add documentation on this in the docs/configuration.md and address my comment on the approach to the test cases?

2024-11-21 23:05 UTC, zachariahmiller commented on tests/watch-jobs.sh
> +      kubectl describe -n "${NAMESPACE}" jobs.batch "${job}"
This script is being called in a zarf action and while it doesnt REALLY matter because its just a test, we have aimed to build all zarf packages and uds task to rely on the built in tools using the calling binary and not expect extra dependencies to be present. So like `./zarf tools kubectl ___` instead of just `kubectl __`. In order to do that this would have to be moved out of being a separate script and instead inlined, which is kind of gross, but better aligned with the assumption of not having extra dependencies in a given environment (CI or otherwise)

2024-11-21 23:05 UTC, zachariahmiller commented on tests/watch-jobs.sh
> +      kubectl describe -n "${NAMESPACE}" jobs.batch "${job}"
Alternatively, this could ideally be a jest test instead of a standalone script being called inside a zarf action.

2024-11-22 01:12 UTC, JoeHCQ1 commented on tasks.yaml
> +      - task: create-dev-package
OK, I was using `create-deploy-test-bundle` as my dev loop while hitting an external cluster. Which was useful, but I see what you're saying. This task is only focused on the bundle creation, presumes the package exists.

2024-11-22 01:14 UTC, JoeHCQ1 commented on tasks/test.yaml
> +        default: ${UDS_ARCH}
If I understood what fixed things for me correctly, without this, the fact `UDS_ARCHITECTURE` is set to amd64 has no effect, because there's no broader architecture input to receive that input.

2024-11-22 01:15 UTC, JoeHCQ1 commented on tasks/test.yaml
> +      - cmd: uds zarf package create tests --architecture="${{ .inputs.architecture }}" --confirm --skip-sbom
I may have mistaken it, but I believe this makes every test bundle an ARM bundle if run on my mac. By referencing `inputs.architecture` the UDS CLI is able to pick up from the `UDS_ARCHITECTURE` env var that I want amd64 bundles.

2024-11-22 01:15 UTC, JoeHCQ1 commented on tasks/test.yaml
> +        cmd: uds zarf package deploy "zarf-package-valkey-test-${{ .inputs.architecture }}-0.1.0.tar.zst" --confirm
See above

2024-11-22 01:17 UTC, JoeHCQ1 commented on tests/valkey/test-job.yaml
> +              echo "${GET_OUTPUT}" | grep "${POD_NAME}" && echo "Got value via replica" || { echo "Failed to get value via replica. Output was: ${GET_OUTPUT}"; exit 1; }
To ensure probabilistically that I read the desired value from a read replica (ideally a number of them), and didn't happen to hit the write replica. It confirms the data replication works.

2024-11-22 01:25 UTC, JoeHCQ1 commented on tests/watch-jobs.sh
> +      kubectl describe -n "${NAMESPACE}" jobs.batch "${job}"
I can definitely get behind replacing calls to `kubectl` with calls to `zarf tools kubectl`. Inlining in Zarf (assuming a multi-line inline) seems to just make for a worse developer experience. I would think (this being a test) that that's not worth the cost to the primary reader.

I don't know Typescript or Javascript so redoing this in jest would be painful. It'd be ChatGPT: "convert this into jest". I already did that once, and can attest that I hadn't a clue what the resulting code did.

2024-11-22 01:29 UTC, JoeHCQ1 commented on tests/zarf.yaml
> +            cmd: sleep 60
Removed it.

2024-11-22 01:29 UTC, JoeHCQ1 commented on tests/watch-jobs.sh
> +      kubectl describe -n "${NAMESPACE}" jobs.batch "${job}"
Pushed up a code-change to make these calls to `uds zarf tools kubectl`

2024-11-22 01:39 UTC, JoeHCQ1 commented on tasks/test.yaml
> +        default: ${UDS_ARCH}
OK, another thing I got confused about trying to debug my builds. Tried removing it - and it does in fact pick up  my `UDS_ARCHITECTURE` variables.

2024-11-22 02:43 UTC, JoeHCQ1 commented on tests/valkey/test-job.yaml
> +              echo "${GET_OUTPUT}" | grep "${POD_NAME}" && echo "Got value via replica" || { echo "Failed to get value via replica. Output was: ${GET_OUTPUT}"; exit 1; }
I also replaced that with a for loop.

2024-11-22 03:56 UTC, Racer159 requested changes

2024-11-22 03:56 UTC, Racer159 commented on docs/configuration.md
> +The default Valkey configuration is a lone read/write node. This is sufficient for most use-cases. GitLab, for example, still recommends a single node architecture even in . It isn't until you reach
```suggestion
```

2024-11-22 04:01 UTC, Racer159 commented on tests/watch-jobs.sh
> +      kubectl describe -n "${NAMESPACE}" jobs.batch "${job}"
I think this is ok for now - we can rewrite it into jest in a refactor later: https://github.com/defenseunicorns/uds-package-valkey/issues/52

2024-11-22 04:02 UTC, Racer159 commented on tests/valkey/test-job.yaml
> +              echo "${GET_OUTPUT}" | grep "${POD_NAME}" && echo "Got value via replica" || { echo "Failed to get value via replica. Output was: ${GET_OUTPUT}"; exit 1; }
ok yeah it makes sense and we can watch for flakes just mostly don't love randomized tests (since they can be flakey - we'll see how this goes and added a tech debt issue to track it: https://github.com/defenseunicorns/uds-package-valkey/issues/52)

2024-11-22 14:54 UTC, zachariahmiller commented on tests/zarf.yaml
> +            cmd: uds zarf tools kubectl -n valkey-test delete -f tests/valkey/test-job.yaml || true
```suggestion
            cmd: ./zarf tools kubectl -n valkey-test delete -f tests/valkey/test-job.yaml || true
```

2024-11-22 15:19 UTC, JoeHCQ1 commented on docs/configuration.md
> +The default Valkey configuration is a lone read/write node. This is sufficient for most use-cases. GitLab, for example, still recommends a single node architecture even in . It isn't until you reach
Oh, yeah, oops

2024-11-22 15:20 UTC, JoeHCQ1 commented on tests/zarf.yaml
> +            cmd: uds zarf tools kubectl -n valkey-test delete -f tests/valkey/test-job.yaml || true
Why do we do that? I delete it everywhere I find it because it breaks locally. I don't have the zarf executable in my working directory, but it is installed in my system path. By calling the executable more generically I maintain compatibility not only with the GitHub pipelines but also with local development.

2024-11-22 15:21 UTC, JoeHCQ1 commented on tests/zarf.yaml
> +            cmd: uds zarf tools kubectl -n valkey-test delete -f tests/valkey/test-job.yaml || true
Also, isn't it more resilient to call zarf via uds?

2024-11-22 15:24 UTC, Racer159 commented on tests/zarf.yaml
> +            cmd: uds zarf tools kubectl -n valkey-test delete -f tests/valkey/test-job.yaml || true
https://docs.zarf.dev/ref/actions/#action-transformations

2024-11-22 15:25 UTC, zachariahmiller commented on tests/zarf.yaml
> +            cmd: uds zarf tools kubectl -n valkey-test delete -f tests/valkey/test-job.yaml || true
referencing zarf inside a zarf action using the syntax `./zarf` internally directs it to use the calling binary (the zarf or uds vendored zarf binary that called the package deploy) it doesnt matter if its on you path of or in the working directory. 

You can do that same thing with uds in tasks ( ie `cmd: ./uds deploy test:latest`), but since zarf isnt aware of uds you cannot do `./uds zarf tools ...`

Your current approach assumes uds is on path, which we cannot assume. The suggested approach makes no such assumption.

2024-11-22 16:19 UTC, JoeHCQ1 commented on tests/zarf.yaml
> +            cmd: uds zarf tools kubectl -n valkey-test delete -f tests/valkey/test-job.yaml || true
Today I Learned ^

2024-11-22 17:08 UTC, Racer159 approved these changes

2024-11-22 18:36 UTC, zachariahmiller approved these changes

2024-11-22 18:42 UTC, merged